# create Pandas Series

In [1]:
 import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [3]:
import pandas as pd

In [5]:
a=pd.Series([1,3,4,5])

In [6]:
a

0    1
1    3
2    4
3    5
dtype: int64

In [7]:
type(a)

pandas.core.series.Series

In [8]:
a[3]

5

In [9]:
pd.date_range(start='01-01-2020',end='31-07-2020')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-07-22', '2020-07-23', '2020-07-24', '2020-07-25',
               '2020-07-26', '2020-07-27', '2020-07-28', '2020-07-29',
               '2020-07-30', '2020-07-31'],
              dtype='datetime64[ns]', length=213, freq='D')

In [10]:
type(a)

pandas.core.series.Series

# pandas dataframe

In [21]:
 import numpy as np
import pandas as pd

In [3]:
temp=np.random.randint(20,100,30)

temp

In [4]:
temp

array([68, 55, 65, 40, 95, 52, 70, 35, 92, 48, 54, 77, 98, 40, 92, 50, 65,
       30, 87, 35, 26, 74, 71, 62, 57, 73, 72, 57, 51, 57])

In [5]:
temp

array([68, 55, 65, 40, 95, 52, 70, 35, 92, 48, 54, 77, 98, 40, 92, 50, 65,
       30, 87, 35, 26, 74, 71, 62, 57, 73, 72, 57, 51, 57])

In [16]:
name=np.random.choice(['star','ankit','geeks','Pya'],30)

In [17]:
random=np.random.choice([10,30,44,5,6,7],30)

In [18]:
a=list(zip(temp,name,random))

In [22]:
df=pd.DataFrame(data=a,columns=['temp','name','random'])

In [23]:
df=pd.DataFrame({'temp': temp,'Name':name,'random':random})

In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
df

    temp   Name  random
0     68  geeks       5
1     55   star       7
2     65   star       7
3     40   star      44
4     95   star      44
5     52   star       6
6     70  geeks      10
7     35   star      44
8     92    Pya      44
9     48  ankit       6
10    54  geeks       6
11    77   star       5
12    98  ankit       6
13    40  ankit       7
14    92  ankit      10
15    50  ankit      10
16    65  geeks       6
17    30    Pya      44
18    87  geeks       6
19    35  geeks      44
20    26   star      10
21    74  geeks       5
22    71  ankit      44
23    62  geeks       6
24    57   star      30
25    73   star       5
26    72  geeks      10
27    57  geeks       6
28    51   star       6
29    57    Pya       6

In [29]:
df.head()

   temp   Name  random
0    45    Pya       5
1    86  ankit       7
2    40   star      30
3    27  ankit       5
4    68  ankit       7

In [30]:
df.head(3)

   temp   Name  random
0    45    Pya       5
1    86  ankit       7
2    40   star      30

In [31]:
df.shape()

TypeError: 'tuple' object is not callable

In [32]:
df.shape

(30, 3)

In [33]:
df.coloumns

AttributeError: 'DataFrame' object has no attribute 'coloumns'

In [34]:
df.columns

Index(['temp', 'Name', 'random'], dtype='object')

In [35]:
df['temp']

0     45
1     86
2     40
3     27
4     68
5     93
6     97
7     36
8     39
9     51
10    21
11    62
12    71
13    81
14    61
15    34
16    45
17    84
18    67
19    28
20    95
21    72
22    25
23    38
24    56
25    43
26    58
27    26
28    95
29    90
Name: temp, dtype: int32

In [36]:
df.describe()

            temp     random
count  30.000000  30.000000
mean   57.800000  17.266667
std    24.333034  14.474552
min    21.000000   5.000000
25%    38.250000   6.250000
50%    57.000000   8.500000
75%    78.750000  30.000000
max    97.000000  44.000000

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   temp    30 non-null     int32
 1   Name    30 non-null     object
 2   random  30 non-null     int32
dtypes: int32(2), object(1)
memory usage: 608.0+ bytes

In [53]:
df.iloc[0:6]

   temp   Name  random
0    45    Pya       5
1    86  ankit       7
2    40   star      30
3    27  ankit       5
4    68  ankit       7
5    93   star       5

In [52]:
df.iloc[1:6,1]

1    ankit
2     star
3    ankit
4    ankit
5     star
Name: Name, dtype: object

In [56]:
df.set_index('temp',inplace=True)

In [15]:
df

NameError: name 'df' is not defined

In [61]:
df.loc[0,:] #you have to use temp it according to temp

KeyError: 0

In [62]:
df.loc[[45,84]]

       Name  random
temp
45      Pya       5
45     star       7
84    geeks       6

In [63]:
df.loc[[45,84],'name':'random']

      random
temp
45         5
45         7
84         6

In [73]:
df.loc[df.Name =='Pya']

     Name  random
temp
45    Pya       5
36    Pya       7
71    Pya       6
56    Pya      10
58    Pya       5
26    Pya      10

# CSV EXCEL

In [27]:
df1=pd.read_csv('Testing.csv')

In [28]:
df1

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Peptic ulcer diseae
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AIDS
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Diabetes
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Gastroenteritis
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Bronchial Asthma
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypertension
11,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Migraine
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Cervical spondylosis
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Paralysis (brain hemorrhage)
14,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jaundice
15,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Malaria
16,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chicken pox
17,0,1,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Dengue
18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Typhoid
19,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,hepatitis A
20,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis B
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis C
22,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis D
23,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis E
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Alcoholic hepatitis
25,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tuberculosis
26,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Common Cold
27,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Pneumonia
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Dimorphic hemmorhoids(piles)
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Heart attack
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Varicose veins
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypothyroidism
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hyperthyroidism
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypoglycemia
34,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Osteoarthristis
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Arthritis
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
37,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
39,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
40,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo

In [80]:
#pip3 install openpyxl

df1.to_excel('star.xlsx')

In [81]:
#pip3 insatll xlrd

df2=pd.read_excel('star.xlsx')

In [82]:
df2

,Unnamed: 0,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,0,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,1,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,2,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,3,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,4,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction
5,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Peptic ulcer diseae
6,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AIDS
7,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Diabetes
8,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Gastroenteritis
9,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Bronchial Asthma
10,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypertension
11,11,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,Migraine
12,12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Cervical spondylosis
13,13,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Paralysis (brain hemorrhage)
14,14,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jaundice
15,15,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Malaria
16,16,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chicken pox
17,17,0,1,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,Dengue
18,18,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Typhoid
19,19,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,hepatitis A
20,20,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis B
21,21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis C
22,22,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis D
23,23,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis E
24,24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Alcoholic hepatitis
25,25,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Tuberculosis
26,26,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Common Cold
27,27,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Pneumonia
28,28,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Dimorphic hemmorhoids(piles)
29,29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Heart attack
30,30,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Varicose veins
31,31,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypothyroidism
32,32,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hyperthyroidism
33,33,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypoglycemia
34,34,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Osteoarthristis
35,35,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Arthritis
36,36,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
37,37,0,1,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
38,38,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
39,39,0,1,0,0,0,0,1,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
40,40,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo

# Merging of Data frames

In [29]:
 df

    temp   Name  random
0     68  geeks       5
1     55   star       7
2     65   star       7
3     40   star      44
4     95   star      44
5     52   star       6
6     70  geeks      10
7     35   star      44
8     92    Pya      44
9     48  ankit       6
10    54  geeks       6
11    77   star       5
12    98  ankit       6
13    40  ankit       7
14    92  ankit      10
15    50  ankit      10
16    65  geeks       6
17    30    Pya      44
18    87  geeks       6
19    35  geeks      44
20    26   star      10
21    74  geeks       5
22    71  ankit      44
23    62  geeks       6
24    57   star      30
25    73   star       5
26    72  geeks      10
27    57  geeks       6
28    51   star       6
29    57    Pya       6

In [35]:
df3=pd.concat([df,df1],axis=0,ignore_index=True)

In [39]:
df3

,temp,Name,random,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,68.0,geeks,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,55.0,star,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,65.0,star,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40.0,star,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,95.0,star,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(vertigo) Paroymsal Positional Vertigo
67,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Acne
68,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Urinary tract infection
69,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,Psoriasis
70,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,Impetigo

In [37]:
df3.describe()

,temp,random,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
count,30.000000,30.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,...,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000
mean,61.600000,16.300000,0.146341,0.170732,0.024390,0.048780,0.024390,0.170732,0.146341,0.048780,...,0.024390,0.024390,0.024390,0.024390,0.024390,0.024390,0.024390,0.024390,0.024390,0.024390
std,19.554698,16.176079,0.357839,0.380949,0.156174,0.218085,0.156174,0.380949,0.357839,0.218085,...,0.156174,0.156174,0.156174,0.156174,0.156174,0.156174,0.156174,0.156174,0.156174,0.156174
min,26.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50.250000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,59.500000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,72.750000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,98.000000,44.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [41]:
def death(x):
        return x>60
    
df3['death']=df3['temp'].apply(death)

In [42]:
df3

,temp,Name,random,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,...,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis,death
0,68.0,geeks,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,55.0,star,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,65.0,star,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,40.0,star,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,95.0,star,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(vertigo) Paroymsal Positional Vertigo,False
67,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Acne,False
68,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Urinary tract infection,False
69,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,Psoriasis,False
70,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,Impetigo,False

In [43]:
d1=pd.DataFrame({
    'city':['kota','jaipur','jodhpur','hisar'],
    'temp':[32,60,80,13]
})

In [44]:
d1

      city  temp
0     kota    32
1   jaipur    60
2  jodhpur    80
3    hisar    13

In [45]:
d2=pd.DataFrame({
    'city':['delhi','kota','jaipur'],
    'Humidty':[77,10,0]
})

In [46]:
d2

     city  Humidty
0   delhi       77
1    kota       10
2  jaipur        0

In [51]:
df=pd.merge(d1,d2,on='city',how='left')

In [52]:
df

      city  temp  Humidty
0     kota    32     10.0
1   jaipur    60      0.0
2  jodhpur    80      NaN
3    hisar    13      NaN

In [54]:
help(pd.DataFrame.pivot_table)

Help on function pivot_table in module pandas.core.frame:

pivot_table(self, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All', observed=False) -> 'DataFrame'
    Create a spreadsheet-style pivot table as a DataFrame.

    The levels in the pivot table will be stored in MultiIndex objects
    (hierarchical indexes) on the index and columns of the result DataFrame.

    Parameters
    ----------
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed,
        it is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types (except list).
        Keys to group by on the pivot table column.  If an array is passed,
        it is being used as the same manner as column values.
    aggfunc : function, list of functions, dict, default numpy.mean
        If list of functions passed, the resulting pivot table will have
        hierarchical columns whose top level are the function names
        (inferred from the function objects themselves)
        If dict is passed, the key is column to aggregate and value
        is function or list of functions.
    fill_value : scalar, default None
        Value to replace missing values with (in the resulting pivot table,
        after aggregation).
    margins : bool, default False
        Add all row / columns (e.g. for subtotal / grand totals).
    dropna : bool, default True
        Do not include columns whose entries are all NaN.
    margins_name : str, default 'All'
        Name of the row / column that will contain the totals
        when margins is True.
    observed : bool, default False
        This only applies if any of the groupers are Categoricals.
        If True: only show observed values for categorical groupers.
        If False: show all values for categorical groupers.

        .. versionchanged:: 0.25.0

    Returns
    -------
    DataFrame
        An Excel style pivot table.

    See Also
    --------
    DataFrame.pivot : Pivot without aggregation that can handle
        non-numeric data.

    Examples
    --------
    >>> df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
    ...                          "bar", "bar", "bar", "bar"],
    ...                    "B": ["one", "one", "one", "two", "two",
    ...                          "one", "one", "two", "two"],
    ...                    "C": ["small", "large", "large", "small",
    ...                          "small", "large", "small", "small",
    ...                          "large"],
    ...                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
    ...                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})
    >>> df
         A    B      C  D  E
    0  foo  one  small  1  2
    1  foo  one  large  2  4
    2  foo  one  large  2  5
    3  foo  two  small  3  5
    4  foo  two  small  3  6
    5  bar  one  large  4  6
    6  bar  one  small  5  8
    7  bar  two  small  6  9
    8  bar  two  large  7  9

    This first example aggregates values by taking the sum.

    >>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
    ...                     columns=['C'], aggfunc=np.sum)
    >>> table
    C        large  small
    A   B
    bar one    4.0    5.0
        two    7.0    6.0
    foo one    4.0    1.0
        two    NaN    6.0

    We can also fill missing values using the `fill_value` parameter.

    >>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
    ...                     columns=['C'], aggfunc=np.sum, fill_value=0)
    >>> table
    C        large  small
    A   B
    bar one      4      5
        two      7      6
    foo one      4      1
        two      0      6

    The next example aggregates by taking the mean across multiple columns.

    >>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
    ...                     aggfunc={'D': np.mean,
    ...                              'E': np.mean})
    >>> table
                    D         E
    A   C
    bar large  5.500000  7.500000
        small  5.500000  8.500000
    foo large  2.000000  4.500000
        small  2.333333  4.333333

    We can also calculate multiple types of aggregations for any given
    value column.

    >>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
    ...                     aggfunc={'D': np.mean,
    ...                              'E': [min, max, np.mean]})
    >>> table
                    D    E
                mean  max      mean  min
    A   C
    bar large  5.500000  9.0  7.500000  6.0
        small  5.500000  9.0  8.500000  8.0
    foo large  2.000000  5.0  4.500000  4.0
        small  2.333333  6.0  4.333333  2.0